chmap: config/channelmap.yml
baseline: [10, 20] #in microseconds relative to the start of the event window
sampling_rate: 1 #MSPS
gain: 6 #encoded gain integer, corresponding to something on order 30 mV/fC (check manual for accurate gains)
pt: 1.2 #us
pulse_threshold: 100 #mV
mv_per_adc: 1800/4096 #mV/adc 
#This is used to identify whether the 0-31/32-63 
#channels have been swapped due to a high speed 
#data line processing error on the part of the ePix.
#It has not been used in a while... 
key_channel: None 
dead_channels": [] #Any channels you want to selectively ignore from some analyses